fix: graphql 전환 후 실패 개선
- glob import가 안되어 있었음
- 불러오기 실패 했을 떄, 명시적으로 실패처리

diff --git a/.github/workflows/velog-sync-graphql.yml b/.github/workflows/velog-sync-graphql.yml
--- a/.github/workflows/velog-sync-graphql.yml
+++ b/.github/workflows/velog-sync-graphql.yml
@@ -44,12 +44,20 @@ jobs:
         GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
         GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
       run: |
-        # 최대 3번 재시도
+        success=false
         for i in {1..3}; do
-          python scripts/update_blog_graphql.py && break
+          if python scripts/update_blog_graphql.py; then
+            success=true
+            break
+          fi
           echo "Attempt $i failed. Retrying in 10 seconds..."
           sleep 10
         done
+
+        if [ "$success" = false ]; then
+          echo "All attempts failed"
+          exit 1  # 명시적으로 실패 상태를 반환
+        fi
 
     - name: Push changes
       env:
@@ -63,7 +71,7 @@ jobs:
         fi
 
     - name: Send notification on failure
-      if: failure()  # workflow가 실패했을 때만 실행
+      if: failure() # workflow가 실패했을 때만 실행
       uses: actions/github-script@v7
       with:
         script: |
